request:
    path: reset-password/request
    methods: post
    controller: App\Controller\V1\ResetPasswordController::request

change:
    path: reset-password/change
    methods: post
    controller: App\Controller\V1\ResetPasswordController::change