request:
    path: reset-password
    methods: get
    controller: App\Controller\Web\ResetPasswordController::request

check_email:
    path: reset-password/check-email
    methods: get
    controller: App\Controller\Web\ResetPasswordController::checkEmail

reset:
    path: reset-password/reset
    methods: get
    controller: App\Controller\Web\ResetPasswordController::reset

success:
    path: reset-password/success
    methods: get
    controller: App\Controller\Web\ResetPasswordController::success