lexik_jwt_authentication:
    token_ttl: '%env(int:JWT_ACCESS_TOKEN_TTL)%'
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    user_identity_field: id
