symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    lifetime: '%env(int:RESET_PASSWORD_LIFETIME)%'
    throttle_limit: '%env(int:RESET_PASSWORD_THROTTLE)%'
    enable_garbage_collection: true